[package]
name = "loc"
authors = ["Ruslan Curbanov"]
description = "A simple CLI tool for counting lines of code, written in Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
